//! Anchor account context structs for every instruction.
//!
//! Organized by concern:
//!
//! 1. **Arcium queue contexts** — `CreateVaultState`, `ComputeQuotes`,
//!    `UpdateBalances`, `UpdateStrategy`, `RevealPerformance`. Each is
//!    marked with `#[queue_computation_accounts(...)]` so Arcium injects
//!    the mempool / executing-pool / cluster / compdef accounts.
//!
//! 2. **Arcium callback contexts** — paired with the above, one per MPC
//!    circuit. Each carries the vault account the callback writes to,
//!    seed-bound to prevent Arcium from delivering a callback against
//!    a spoofed vault.
//!
//! 3. **Arcium comp-def init contexts** — one-shot registration of each
//!    computation definition on-chain.
//!
//! 4. **Non-Arcium contexts** — `InitializeVault`, `Deposit`, `Withdraw`,
//!    `ExecuteRebalance`. Plain SPL + PDA flow.
//!
//! Every vault reference is bound to the `[b"vault", vault.authority]`
//! PDA so a caller cannot pass an arbitrary Vault account that happens
//! to deserialize correctly.

use anchor_lang::prelude::*;
use anchor_spl::token_interface::{Mint, TokenAccount, TokenInterface};
use arcium_anchor::prelude::*;

// `ArciumSignerAccount` is emitted by the #[arcium_program] macro at the
// crate root (as a sibling of the program module). `ID` / `ID_CONST`
// are generated by declare_id! also at the crate root and referenced
// inside the derive_*_pda!() macros used below.
use crate::{ArciumSignerAccount, ID, ID_CONST};

use crate::constants::*;
use crate::errors::ErrorCode;
use crate::state::Vault;

// =============================================================
// Arcium queue-computation contexts
// =============================================================

#[queue_computation_accounts("init_vault_state", authority)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct CreateVaultState<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", authority.key().as_ref()],
        bump = vault.bump,
        has_one = authority @ ErrorCode::Unauthorized,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        init_if_needed, space = 9, payer = authority,
        seeds = [&SIGN_PDA_SEED], bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(mut, address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub mempool_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub executing_pool: UncheckedAccount<'info>,
    #[account(mut, address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_INIT_VAULT_STATE))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(mut, address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

#[queue_computation_accounts("compute_quotes", cranker)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct ComputeQuotes<'info> {
    // Cranker must equal `vault.cranker` — gates who can drive the MPC
    // quote flow. Without this, an attacker could queue compute_quotes
    // with an adversarial `oracle_price` and consume the quote slot
    // before the legitimate cranker. Defaults to `vault.authority` at
    // init; can be delegated via a future `set_cranker` instruction.
    #[account(
        mut,
        constraint = cranker.key() == vault.cranker @ ErrorCode::Unauthorized,
    )]
    pub cranker: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        init_if_needed, space = 9, payer = cranker,
        seeds = [&SIGN_PDA_SEED], bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(mut, address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub mempool_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub executing_pool: UncheckedAccount<'info>,
    #[account(mut, address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_COMPUTE_QUOTES))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(mut, address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

#[queue_computation_accounts("update_balances", cranker)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct UpdateBalances<'info> {
    // Cranker gate: only the vault's cranker can apply post-trade deltas
    // to the encrypted state. Without this, any signer could submit
    // fake base/quote deltas and corrupt the encrypted balances, which
    // would then mis-price subsequent quotes and deposits/withdrawals.
    // Defaults to `vault.authority` at init.
    #[account(
        mut,
        constraint = cranker.key() == vault.cranker @ ErrorCode::Unauthorized,
    )]
    pub cranker: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        init_if_needed, space = 9, payer = cranker,
        seeds = [&SIGN_PDA_SEED], bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(mut, address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub mempool_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub executing_pool: UncheckedAccount<'info>,
    #[account(mut, address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_UPDATE_BALANCES))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(mut, address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

#[queue_computation_accounts("update_strategy", authority)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct UpdateStrategy<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", authority.key().as_ref()],
        bump = vault.bump,
        has_one = authority @ ErrorCode::Unauthorized,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        init_if_needed, space = 9, payer = authority,
        seeds = [&SIGN_PDA_SEED], bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(mut, address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub mempool_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub executing_pool: UncheckedAccount<'info>,
    #[account(mut, address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_UPDATE_STRATEGY))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(mut, address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

#[queue_computation_accounts("reveal_performance", caller)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct RevealPerformance<'info> {
    #[account(mut)]
    pub caller: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        init_if_needed, space = 9, payer = caller,
        seeds = [&SIGN_PDA_SEED], bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    #[account(mut, address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub mempool_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub executing_pool: UncheckedAccount<'info>,
    #[account(mut, address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet))]
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_REVEAL_PERFORMANCE))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(mut, address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,
    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

// =============================================================
// Arcium callback contexts
// =============================================================

#[callback_accounts("init_vault_state")]
#[derive(Accounts)]
pub struct InitVaultStateCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_INIT_VAULT_STATE))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions sysvar
    pub instructions_sysvar: AccountInfo<'info>,
    // Custom callback account: vault to write encrypted state into.
    // Seed binding ensures Arcium can only deliver the callback to a
    // legitimate vault PDA, not an arbitrary account that happens to
    // deserialize as Vault.
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Account<'info, Vault>,
}

#[callback_accounts("compute_quotes")]
#[derive(Accounts)]
pub struct ComputeQuotesCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_COMPUTE_QUOTES))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions sysvar
    pub instructions_sysvar: AccountInfo<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Account<'info, Vault>,
}

#[callback_accounts("update_balances")]
#[derive(Accounts)]
pub struct UpdateBalancesCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_UPDATE_BALANCES))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions sysvar
    pub instructions_sysvar: AccountInfo<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Account<'info, Vault>,
}

#[callback_accounts("update_strategy")]
#[derive(Accounts)]
pub struct UpdateStrategyCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_UPDATE_STRATEGY))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions sysvar
    pub instructions_sysvar: AccountInfo<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Account<'info, Vault>,
}

#[callback_accounts("reveal_performance")]
#[derive(Accounts)]
pub struct RevealPerformanceCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,
    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_REVEAL_PERFORMANCE))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,
    /// CHECK: checked by arcium program
    pub computation_account: UncheckedAccount<'info>,
    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Box<Account<'info, Cluster>>,
    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions sysvar
    pub instructions_sysvar: AccountInfo<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Account<'info, Vault>,
}

// =============================================================
// Arcium computation-definition init contexts
// =============================================================

#[init_computation_definition_accounts("init_vault_state", payer)]
#[derive(Accounts)]
pub struct InitVaultStateCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(mut, address = derive_mxe_pda!())]
    pub mxe_account: Box<Account<'info, MXEAccount>>,
    #[account(mut)]
    /// CHECK: checked by arcium program
    pub comp_def_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot))]
    /// CHECK: checked by arcium program
    pub address_lookup_table: UncheckedAccount<'info>,
    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: lut_program
    pub lut_program: UncheckedAccount<'info>,
    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

#[init_computation_definition_accounts("compute_quotes", payer)]
#[derive(Accounts)]
pub struct InitComputeQuotesCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(mut, address = derive_mxe_pda!())]
    pub mxe_account: Box<Account<'info, MXEAccount>>,
    #[account(mut)]
    /// CHECK: checked by arcium program
    pub comp_def_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot))]
    /// CHECK: checked by arcium program
    pub address_lookup_table: UncheckedAccount<'info>,
    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: lut_program
    pub lut_program: UncheckedAccount<'info>,
    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

#[init_computation_definition_accounts("update_balances", payer)]
#[derive(Accounts)]
pub struct InitUpdateBalancesCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(mut, address = derive_mxe_pda!())]
    pub mxe_account: Box<Account<'info, MXEAccount>>,
    #[account(mut)]
    /// CHECK: checked by arcium program
    pub comp_def_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot))]
    /// CHECK: checked by arcium program
    pub address_lookup_table: UncheckedAccount<'info>,
    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: lut_program
    pub lut_program: UncheckedAccount<'info>,
    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

#[init_computation_definition_accounts("update_strategy", payer)]
#[derive(Accounts)]
pub struct InitUpdateStrategyCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(mut, address = derive_mxe_pda!())]
    pub mxe_account: Box<Account<'info, MXEAccount>>,
    #[account(mut)]
    /// CHECK: checked by arcium program
    pub comp_def_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot))]
    /// CHECK: checked by arcium program
    pub address_lookup_table: UncheckedAccount<'info>,
    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: lut_program
    pub lut_program: UncheckedAccount<'info>,
    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

#[init_computation_definition_accounts("reveal_performance", payer)]
#[derive(Accounts)]
pub struct InitRevealPerformanceCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(mut, address = derive_mxe_pda!())]
    pub mxe_account: Box<Account<'info, MXEAccount>>,
    #[account(mut)]
    /// CHECK: checked by arcium program
    pub comp_def_account: UncheckedAccount<'info>,
    #[account(mut, address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot))]
    /// CHECK: checked by arcium program
    pub address_lookup_table: UncheckedAccount<'info>,
    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: lut_program
    pub lut_program: UncheckedAccount<'info>,
    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

// =============================================================
// Non-Arcium contexts (SPL + PDA flow)
// =============================================================

#[derive(Accounts)]
pub struct InitializeVault<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        init,
        payer = authority,
        space = 8 + Vault::INIT_SPACE,
        seeds = [b"vault", authority.key().as_ref()],
        bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    // Token A and B mints must be distinct so that we never accidentally
    // create a "self-pair" (e.g. SOL/SOL) where deposit/withdraw arithmetic
    // would conflate the two sides.
    #[account(
        constraint = token_a_mint.key() != token_b_mint.key() @ ErrorCode::DuplicateMint,
    )]
    pub token_a_mint: InterfaceAccount<'info, Mint>,
    pub token_b_mint: InterfaceAccount<'info, Mint>,
    // Vault token accounts must be (a) owned by the vault PDA, (b) of the
    // expected mint, AND (c) free of any side-channel that would let a
    // creator drain funds out-of-band: no delegate, no close authority.
    #[account(
        constraint = token_a_vault.mint == token_a_mint.key() @ ErrorCode::MintMismatch,
        constraint = token_a_vault.owner == vault.key() @ ErrorCode::VaultOwnerMismatch,
        constraint = token_a_vault.delegate.is_none() @ ErrorCode::InvalidVaultAccount,
        constraint = token_a_vault.close_authority.is_none() @ ErrorCode::InvalidVaultAccount,
        constraint = token_a_vault.key() != token_b_vault.key() @ ErrorCode::DuplicateMint,
    )]
    pub token_a_vault: InterfaceAccount<'info, TokenAccount>,
    #[account(
        constraint = token_b_vault.mint == token_b_mint.key() @ ErrorCode::MintMismatch,
        constraint = token_b_vault.owner == vault.key() @ ErrorCode::VaultOwnerMismatch,
        constraint = token_b_vault.delegate.is_none() @ ErrorCode::InvalidVaultAccount,
        constraint = token_b_vault.close_authority.is_none() @ ErrorCode::InvalidVaultAccount,
    )]
    pub token_b_vault: InterfaceAccount<'info, TokenAccount>,
    // Share mint must be (a) authority = vault PDA, (b) zero supply at init,
    // (c) NO freeze authority (otherwise the creator could freeze user
    // share tokens after the fact and lock LPs out of withdrawals).
    #[account(
        constraint = share_mint.mint_authority.contains(&vault.key()) @ ErrorCode::VaultOwnerMismatch,
        constraint = share_mint.supply == 0 @ ErrorCode::InvalidAmount,
        constraint = share_mint.freeze_authority.is_none() @ ErrorCode::InvalidMint,
    )]
    pub share_mint: InterfaceAccount<'info, Mint>,
    pub token_program: Interface<'info, TokenInterface>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Deposit<'info> {
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        mut,
        constraint = user_token_account.mint == vault.token_b_mint @ ErrorCode::MintMismatch,
        constraint = user_token_account.owner == user.key() @ ErrorCode::Unauthorized,
    )]
    pub user_token_account: InterfaceAccount<'info, TokenAccount>,
    // Quote mint, required by transfer_checked. Pinned to vault.token_b_mint
    // to prevent a caller from substituting a different mint at call time.
    #[account(address = vault.token_b_mint @ ErrorCode::MintMismatch)]
    pub token_b_mint: InterfaceAccount<'info, Mint>,
    #[account(
        mut,
        address = vault.token_b_vault @ ErrorCode::VaultOwnerMismatch,
    )]
    pub vault_token_b: InterfaceAccount<'info, TokenAccount>,
    #[account(
        mut,
        address = vault.share_mint @ ErrorCode::MintMismatch,
    )]
    pub share_mint: InterfaceAccount<'info, Mint>,
    #[account(
        mut,
        constraint = user_share_account.mint == vault.share_mint @ ErrorCode::MintMismatch,
        constraint = user_share_account.owner == user.key() @ ErrorCode::Unauthorized,
    )]
    pub user_share_account: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

#[derive(Accounts)]
pub struct Withdraw<'info> {
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        mut,
        constraint = user_token_account.mint == vault.token_b_mint @ ErrorCode::MintMismatch,
        constraint = user_token_account.owner == user.key() @ ErrorCode::Unauthorized,
    )]
    pub user_token_account: InterfaceAccount<'info, TokenAccount>,
    // Quote mint, required by transfer_checked.
    #[account(address = vault.token_b_mint @ ErrorCode::MintMismatch)]
    pub token_b_mint: InterfaceAccount<'info, Mint>,
    #[account(
        mut,
        address = vault.token_b_vault @ ErrorCode::VaultOwnerMismatch,
    )]
    pub vault_token_b: InterfaceAccount<'info, TokenAccount>,
    #[account(
        mut,
        address = vault.share_mint @ ErrorCode::MintMismatch,
    )]
    pub share_mint: InterfaceAccount<'info, Mint>,
    #[account(
        mut,
        constraint = user_share_account.mint == vault.share_mint @ ErrorCode::MintMismatch,
        constraint = user_share_account.owner == user.key() @ ErrorCode::Unauthorized,
    )]
    pub user_share_account: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

/// Authority-only: re-assign `vault.cranker` to a new pubkey. Lets the
/// vault owner delegate MPC cranking to a separate keypair (e.g. a hot
/// wallet on a cranking node) without transferring vault ownership.
#[derive(Accounts)]
pub struct SetCranker<'info> {
    pub authority: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", authority.key().as_ref()],
        bump = vault.bump,
        has_one = authority @ ErrorCode::Unauthorized,
    )]
    pub vault: Box<Account<'info, Vault>>,
}

#[derive(Accounts)]
pub struct ExecuteRebalance<'info> {
    // Cranker gate: only `vault.cranker` can execute a rebalance.
    // Shares the same trust boundary as compute_quotes / update_balances
    // so a single delegation (via future `set_cranker`) covers the whole
    // MPC rebalance pipeline. Defaults to `vault.authority` at init, so
    // a fresh vault behaves identically to the pre-delegation flow.
    #[account(
        mut,
        constraint = cranker.key() == vault.cranker @ ErrorCode::Unauthorized,
    )]
    pub cranker: Signer<'info>,
    #[account(
        mut,
        seeds = [b"vault", vault.authority.as_ref()],
        bump = vault.bump,
    )]
    pub vault: Box<Account<'info, Vault>>,
    #[account(
        mut,
        address = vault.token_a_vault @ ErrorCode::VaultOwnerMismatch,
    )]
    pub vault_token_a: InterfaceAccount<'info, TokenAccount>,
    #[account(
        mut,
        address = vault.token_b_vault @ ErrorCode::VaultOwnerMismatch,
    )]
    pub vault_token_b: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
    // --- Meteora DLMM accounts will be added here ---
    // pub dlmm_program: ...
    // pub lb_pair: ...
    // pub bin_array_lower: ...
    // pub bin_array_upper: ...
    // etc.
}
