//! Meteora DLMM CPI helpers — hand-rolled swap instruction.
//!
//! We intentionally avoid `declare_program!(dlmm)` here. The DLMM IDL
//! declares zero-copy account types (`Position`, `PositionV2`, `BinArray`,
//! `Oracle`) whose generated bytemuck `AnyBitPattern` bounds fail to
//! compile. Since ShadowPool only needs the `swap` instruction, a narrow
//! hand-rolled CPI is cleaner, fully auditable, and avoids pulling in
//! the full DLMM type surface.
//!
//! **Source of truth:** `idls/dlmm.json` v0.8.2, pinned in repo.
//! Program: `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo` (same on
//! mainnet-beta and devnet).
//!
//! **Account ordering matches the IDL exactly.** Any drift is a bug —
//! refer to the IDL when adding new instructions.

use anchor_lang::prelude::*;
use anchor_lang::solana_program::{
    instruction::{AccountMeta, Instruction},
    program::invoke_signed,
};

/// Meteora DLMM program ID. Same on mainnet-beta and devnet (verified
/// against the vendored IDL's `.address` field and a live devnet RPC
/// query 2026-04-16).
pub mod dlmm_program {
    use anchor_lang::prelude::declare_id;
    declare_id!("LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo");
}

/// Anchor instruction discriminator for `swap`. Taken verbatim from
/// `idls/dlmm.json` v0.8.2 and pinned as a constant so a future IDL
/// version bump does not silently alter the CPI target.
pub const SWAP_DISCRIMINATOR: [u8; 8] = [248, 198, 158, 145, 225, 117, 135, 200];

/// Wraps every account the DLMM `swap` instruction expects, in IDL
/// order. Optional accounts (`bin_array_bitmap_extension`, `host_fee_in`)
/// are typed `Option<&AccountInfo>`; callers pass `None` to signal
/// absence, and we substitute the DLMM program id as the Anchor-idiomatic
/// placeholder.
pub struct SwapCpiAccounts<'a, 'info> {
    pub lb_pair: &'a AccountInfo<'info>,
    pub bin_array_bitmap_extension: Option<&'a AccountInfo<'info>>,
    pub reserve_x: &'a AccountInfo<'info>,
    pub reserve_y: &'a AccountInfo<'info>,
    pub user_token_in: &'a AccountInfo<'info>,
    pub user_token_out: &'a AccountInfo<'info>,
    pub token_x_mint: &'a AccountInfo<'info>,
    pub token_y_mint: &'a AccountInfo<'info>,
    pub oracle: &'a AccountInfo<'info>,
    pub host_fee_in: Option<&'a AccountInfo<'info>>,
    pub user: &'a AccountInfo<'info>,
    pub token_x_program: &'a AccountInfo<'info>,
    pub token_y_program: &'a AccountInfo<'info>,
    pub event_authority: &'a AccountInfo<'info>,
    pub dlmm_program: &'a AccountInfo<'info>,
    /// Bin arrays the swap traverses. Client-side pre-computed from the
    /// pool's `active_id`. At least one array is required; typical swaps
    /// pass three (active-1, active, active+1).
    pub bin_arrays: &'a [AccountInfo<'info>],
}

/// Issue the DLMM `swap` CPI with a PDA signer.
///
/// Args:
/// - `amount_in` — token_in amount in raw (mint-decimal) units.
/// - `min_amount_out` — slippage floor; DLMM reverts with
///   `ExceededAmountSlippageTolerance` if the swap would deliver less.
///
/// Signer seeds flow through to `invoke_signed`; ShadowPool's vault PDA
/// uses `[b"vault", vault.authority.as_ref(), &[vault.bump]]`.
pub fn swap<'info>(
    accounts: SwapCpiAccounts<'_, 'info>,
    signer_seeds: &[&[&[u8]]],
    amount_in: u64,
    min_amount_out: u64,
) -> Result<()> {
    // Anchor-idiomatic placeholder for absent optional accounts: the
    // callee program id itself. Meteora's CPI example uses this
    // convention for `bin_array_bitmap_extension` / `host_fee_in`.
    let dlmm_id = dlmm_program::ID;
    let bitmap_ext_info = accounts
        .bin_array_bitmap_extension
        .unwrap_or(accounts.dlmm_program);
    let host_fee_info = accounts.host_fee_in.unwrap_or(accounts.dlmm_program);

    // --- Instruction data: discriminator + amount_in + min_amount_out
    let mut data = Vec::with_capacity(8 + 8 + 8);
    data.extend_from_slice(&SWAP_DISCRIMINATOR);
    data.extend_from_slice(&amount_in.to_le_bytes());
    data.extend_from_slice(&min_amount_out.to_le_bytes());

    // --- AccountMetas in IDL order. Writable/signer flags mirror the IDL.
    let mut metas = vec![
        AccountMeta::new(accounts.lb_pair.key(), false),
        // bin_array_bitmap_extension is read-only in the IDL; when
        // omitted we pass the program id (read-only).
        if accounts.bin_array_bitmap_extension.is_some() {
            AccountMeta::new_readonly(bitmap_ext_info.key(), false)
        } else {
            AccountMeta::new_readonly(dlmm_id, false)
        },
        AccountMeta::new(accounts.reserve_x.key(), false),
        AccountMeta::new(accounts.reserve_y.key(), false),
        AccountMeta::new(accounts.user_token_in.key(), false),
        AccountMeta::new(accounts.user_token_out.key(), false),
        AccountMeta::new_readonly(accounts.token_x_mint.key(), false),
        AccountMeta::new_readonly(accounts.token_y_mint.key(), false),
        AccountMeta::new(accounts.oracle.key(), false),
        // host_fee_in is writable in the IDL; omitted → program id (ro).
        if accounts.host_fee_in.is_some() {
            AccountMeta::new(host_fee_info.key(), false)
        } else {
            AccountMeta::new_readonly(dlmm_id, false)
        },
        AccountMeta::new_readonly(accounts.user.key(), true),
        AccountMeta::new_readonly(accounts.token_x_program.key(), false),
        AccountMeta::new_readonly(accounts.token_y_program.key(), false),
        AccountMeta::new_readonly(accounts.event_authority.key(), false),
        AccountMeta::new_readonly(accounts.dlmm_program.key(), false),
    ];
    // Bin arrays — all writable; DLMM mutates them on swap.
    for ba in accounts.bin_arrays {
        metas.push(AccountMeta::new(ba.key(), false));
    }

    // --- AccountInfos parallel to metas. invoke_signed requires all
    // referenced accounts be in this list (both writable and readable).
    let mut infos = vec![
        accounts.lb_pair.clone(),
        bitmap_ext_info.clone(),
        accounts.reserve_x.clone(),
        accounts.reserve_y.clone(),
        accounts.user_token_in.clone(),
        accounts.user_token_out.clone(),
        accounts.token_x_mint.clone(),
        accounts.token_y_mint.clone(),
        accounts.oracle.clone(),
        host_fee_info.clone(),
        accounts.user.clone(),
        accounts.token_x_program.clone(),
        accounts.token_y_program.clone(),
        accounts.event_authority.clone(),
        accounts.dlmm_program.clone(),
    ];
    for ba in accounts.bin_arrays {
        infos.push(ba.clone());
    }

    let ix = Instruction {
        program_id: dlmm_id,
        accounts: metas,
        data,
    };

    invoke_signed(&ix, &infos, signer_seeds).map_err(Into::into)
}
